# Generated by Django 3.2.5 on 2021-08-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_admin_reg1'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_reg_form_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('repeat_password', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='admin_reg1',
        ),
        migrations.DeleteModel(
            name='admin_reg_form',
        ),
    ]
