# Generated by Django 3.2.5 on 2021-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_auto_20210802_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('messages', models.TextField()),
            ],
        ),
    ]
