# Generated by Django 3.2.5 on 2021-08-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_contact_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_reg',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
