# Generated by Django 3.2.5 on 2021-08-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_usermanagement_add_database'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usermanagement_add_database',
            new_name='usermanagement_add_database_new',
        ),
    ]
