# Generated by Django 3.2.5 on 2021-08-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_rename_usermanagement_add_database_usermanagement_add_database_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_add_database_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categoryadd_file', models.FileField(null=True, upload_to='documents')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
