# Generated by Django 3.2.5 on 2021-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_category_add_database_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit_add_database_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('sparepart_name', models.CharField(max_length=100)),
            ],
        ),
    ]
