# Generated by Django 3.2.5 on 2021-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_unit_add_database_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='tax_add_database_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('Item_name', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
            ],
        ),
    ]
