# Generated by Django 3.2.5 on 2021-08-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_tax_add_database_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tax_add_database_new',
            new_name='taxadd_database_new',
        ),
    ]
