# Generated by Django 3.2.5 on 2021-08-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_productadd_database_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_1',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_2',
            new_name='enter_barcode',
        ),
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_3',
            new_name='product_cost',
        ),
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_4',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_5',
            new_name='quantatity',
        ),
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_6',
            new_name='sales_price',
        ),
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_7',
            new_name='select_brand',
        ),
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_8',
            new_name='select_unit',
        ),
        migrations.RenameField(
            model_name='productadd_database_new',
            old_name='item_9',
            new_name='tax_type',
        ),
    ]
