# Generated by Django 3.2.5 on 2021-08-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_auto_20210811_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotations_database_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_warehouse', models.CharField(max_length=100)),
                ('to_warehouse', models.CharField(max_length=100)),
                ('shipping_cost', models.CharField(max_length=100)),
                ('select_state', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantatity', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
            ],
        ),
    ]
