# Generated by Django 3.2.5 on 2021-08-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0016_purchase_database_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocktransfer_database_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=100)),
                ('stocks_info', models.CharField(max_length=100)),
                ('Shipping_Cost', models.CharField(max_length=100)),
                ('Total_Amount', models.CharField(max_length=100)),
            ],
        ),
    ]
